# Generated by Django 5.0.7 on 2024-07-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapi', '0004_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripeapi.customuser')),
            ],
        ),
    ]
