# Generated by Django 5.0.7 on 2024-07-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapi', '0005_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='custom_user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
